version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
  labels:
  - upgrade
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
  - dependency-name: nuxt
    versions:
    - 2.14.12
  - dependency-name: "@nuxtjs/pwa"
    versions:
    - 3.3.3
  - dependency-name: "@babel/runtime-corejs3"
    versions:
    - 7.12.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
